// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public interface DoubleNestedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bkbn.kompendium.protobufjavaconverter.DoubleNestedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.NestedMessage nested_field = 1;</code>
   * @return Whether the nestedField field is set.
   */
  boolean hasNestedField();
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.NestedMessage nested_field = 1;</code>
   * @return The nestedField.
   */
  io.bkbn.kompendium.protobufjavaconverter.NestedMessage getNestedField();
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.NestedMessage nested_field = 1;</code>
   */
  io.bkbn.kompendium.protobufjavaconverter.NestedMessageOrBuilder getNestedFieldOrBuilder();
}
