// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public interface EnumMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bkbn.kompendium.protobufjavaconverter.EnumMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
   * @return The enum numeric value on the wire for corpus.
   */
  int getCorpusValue();
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
   * @return The corpus.
   */
  io.bkbn.kompendium.protobufjavaconverter.Corpus getCorpus();
}
