// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

/**
 * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.EnumMessage}
 */
public final class EnumMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.bkbn.kompendium.protobufjavaconverter.EnumMessage)
    EnumMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnumMessage.newBuilder() to construct.
  private EnumMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnumMessage() {
    corpus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnumMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnumMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            corpus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bkbn.kompendium.protobufjavaconverter.EnumMessage.class, io.bkbn.kompendium.protobufjavaconverter.EnumMessage.Builder.class);
  }

  public static final int CORPUS_FIELD_NUMBER = 1;
  private int corpus_;
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
   * @return The enum numeric value on the wire for corpus.
   */
  @java.lang.Override public int getCorpusValue() {
    return corpus_;
  }
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
   * @return The corpus.
   */
  @java.lang.Override public io.bkbn.kompendium.protobufjavaconverter.Corpus getCorpus() {
    @SuppressWarnings("deprecation")
    io.bkbn.kompendium.protobufjavaconverter.Corpus result = io.bkbn.kompendium.protobufjavaconverter.Corpus.valueOf(corpus_);
    return result == null ? io.bkbn.kompendium.protobufjavaconverter.Corpus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (corpus_ != io.bkbn.kompendium.protobufjavaconverter.Corpus.CORPUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, corpus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (corpus_ != io.bkbn.kompendium.protobufjavaconverter.Corpus.CORPUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, corpus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bkbn.kompendium.protobufjavaconverter.EnumMessage)) {
      return super.equals(obj);
    }
    io.bkbn.kompendium.protobufjavaconverter.EnumMessage other = (io.bkbn.kompendium.protobufjavaconverter.EnumMessage) obj;

    if (corpus_ != other.corpus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CORPUS_FIELD_NUMBER;
    hash = (53 * hash) + corpus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bkbn.kompendium.protobufjavaconverter.EnumMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.EnumMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bkbn.kompendium.protobufjavaconverter.EnumMessage)
      io.bkbn.kompendium.protobufjavaconverter.EnumMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bkbn.kompendium.protobufjavaconverter.EnumMessage.class, io.bkbn.kompendium.protobufjavaconverter.EnumMessage.Builder.class);
    }

    // Construct using io.bkbn.kompendium.protobufjavaconverter.EnumMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      corpus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_descriptor;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.EnumMessage getDefaultInstanceForType() {
      return io.bkbn.kompendium.protobufjavaconverter.EnumMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.EnumMessage build() {
      io.bkbn.kompendium.protobufjavaconverter.EnumMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.EnumMessage buildPartial() {
      io.bkbn.kompendium.protobufjavaconverter.EnumMessage result = new io.bkbn.kompendium.protobufjavaconverter.EnumMessage(this);
      result.corpus_ = corpus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bkbn.kompendium.protobufjavaconverter.EnumMessage) {
        return mergeFrom((io.bkbn.kompendium.protobufjavaconverter.EnumMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bkbn.kompendium.protobufjavaconverter.EnumMessage other) {
      if (other == io.bkbn.kompendium.protobufjavaconverter.EnumMessage.getDefaultInstance()) return this;
      if (other.corpus_ != 0) {
        setCorpusValue(other.getCorpusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bkbn.kompendium.protobufjavaconverter.EnumMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bkbn.kompendium.protobufjavaconverter.EnumMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int corpus_ = 0;
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
     * @return The enum numeric value on the wire for corpus.
     */
    @java.lang.Override public int getCorpusValue() {
      return corpus_;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
     * @param value The enum numeric value on the wire for corpus to set.
     * @return This builder for chaining.
     */
    public Builder setCorpusValue(int value) {
      
      corpus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
     * @return The corpus.
     */
    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.Corpus getCorpus() {
      @SuppressWarnings("deprecation")
      io.bkbn.kompendium.protobufjavaconverter.Corpus result = io.bkbn.kompendium.protobufjavaconverter.Corpus.valueOf(corpus_);
      return result == null ? io.bkbn.kompendium.protobufjavaconverter.Corpus.UNRECOGNIZED : result;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
     * @param value The corpus to set.
     * @return This builder for chaining.
     */
    public Builder setCorpus(io.bkbn.kompendium.protobufjavaconverter.Corpus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      corpus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.Corpus corpus = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorpus() {
      
      corpus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.bkbn.kompendium.protobufjavaconverter.EnumMessage)
  }

  // @@protoc_insertion_point(class_scope:io.bkbn.kompendium.protobufjavaconverter.EnumMessage)
  private static final io.bkbn.kompendium.protobufjavaconverter.EnumMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bkbn.kompendium.protobufjavaconverter.EnumMessage();
  }

  public static io.bkbn.kompendium.protobufjavaconverter.EnumMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnumMessage>
      PARSER = new com.google.protobuf.AbstractParser<EnumMessage>() {
    @java.lang.Override
    public EnumMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnumMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnumMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnumMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.EnumMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

