// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

/**
 * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.GoogleTypes}
 */
public final class GoogleTypes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.bkbn.kompendium.protobufjavaconverter.GoogleTypes)
    GoogleTypesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GoogleTypes.newBuilder() to construct.
  private GoogleTypes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GoogleTypes() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GoogleTypes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GoogleTypes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestampField_ != null) {
              subBuilder = timestampField_.toBuilder();
            }
            timestampField_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestampField_);
              timestampField_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (durationField_ != null) {
              subBuilder = durationField_.toBuilder();
            }
            durationField_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(durationField_);
              durationField_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bkbn.kompendium.protobufjavaconverter.GoogleTypes.class, io.bkbn.kompendium.protobufjavaconverter.GoogleTypes.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timestampField_;
  /**
   * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
   * @return Whether the timestampField field is set.
   */
  @java.lang.Override
  public boolean hasTimestampField() {
    return timestampField_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
   * @return The timestampField.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestampField() {
    return timestampField_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestampField_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampFieldOrBuilder() {
    return getTimestampField();
  }

  public static final int DURATION_FIELD_FIELD_NUMBER = 2;
  private com.google.protobuf.Duration durationField_;
  /**
   * <pre>
   * TODO value types
   * </pre>
   *
   * <code>.google.protobuf.Duration duration_field = 2;</code>
   * @return Whether the durationField field is set.
   */
  @java.lang.Override
  public boolean hasDurationField() {
    return durationField_ != null;
  }
  /**
   * <pre>
   * TODO value types
   * </pre>
   *
   * <code>.google.protobuf.Duration duration_field = 2;</code>
   * @return The durationField.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getDurationField() {
    return durationField_ == null ? com.google.protobuf.Duration.getDefaultInstance() : durationField_;
  }
  /**
   * <pre>
   * TODO value types
   * </pre>
   *
   * <code>.google.protobuf.Duration duration_field = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getDurationFieldOrBuilder() {
    return getDurationField();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestampField_ != null) {
      output.writeMessage(1, getTimestampField());
    }
    if (durationField_ != null) {
      output.writeMessage(2, getDurationField());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestampField_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTimestampField());
    }
    if (durationField_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDurationField());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bkbn.kompendium.protobufjavaconverter.GoogleTypes)) {
      return super.equals(obj);
    }
    io.bkbn.kompendium.protobufjavaconverter.GoogleTypes other = (io.bkbn.kompendium.protobufjavaconverter.GoogleTypes) obj;

    if (hasTimestampField() != other.hasTimestampField()) return false;
    if (hasTimestampField()) {
      if (!getTimestampField()
          .equals(other.getTimestampField())) return false;
    }
    if (hasDurationField() != other.hasDurationField()) return false;
    if (hasDurationField()) {
      if (!getDurationField()
          .equals(other.getDurationField())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTimestampField()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampField().hashCode();
    }
    if (hasDurationField()) {
      hash = (37 * hash) + DURATION_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getDurationField().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bkbn.kompendium.protobufjavaconverter.GoogleTypes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.GoogleTypes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bkbn.kompendium.protobufjavaconverter.GoogleTypes)
      io.bkbn.kompendium.protobufjavaconverter.GoogleTypesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bkbn.kompendium.protobufjavaconverter.GoogleTypes.class, io.bkbn.kompendium.protobufjavaconverter.GoogleTypes.Builder.class);
    }

    // Construct using io.bkbn.kompendium.protobufjavaconverter.GoogleTypes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (timestampFieldBuilder_ == null) {
        timestampField_ = null;
      } else {
        timestampField_ = null;
        timestampFieldBuilder_ = null;
      }
      if (durationFieldBuilder_ == null) {
        durationField_ = null;
      } else {
        durationField_ = null;
        durationFieldBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_descriptor;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.GoogleTypes getDefaultInstanceForType() {
      return io.bkbn.kompendium.protobufjavaconverter.GoogleTypes.getDefaultInstance();
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.GoogleTypes build() {
      io.bkbn.kompendium.protobufjavaconverter.GoogleTypes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.GoogleTypes buildPartial() {
      io.bkbn.kompendium.protobufjavaconverter.GoogleTypes result = new io.bkbn.kompendium.protobufjavaconverter.GoogleTypes(this);
      if (timestampFieldBuilder_ == null) {
        result.timestampField_ = timestampField_;
      } else {
        result.timestampField_ = timestampFieldBuilder_.build();
      }
      if (durationFieldBuilder_ == null) {
        result.durationField_ = durationField_;
      } else {
        result.durationField_ = durationFieldBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bkbn.kompendium.protobufjavaconverter.GoogleTypes) {
        return mergeFrom((io.bkbn.kompendium.protobufjavaconverter.GoogleTypes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bkbn.kompendium.protobufjavaconverter.GoogleTypes other) {
      if (other == io.bkbn.kompendium.protobufjavaconverter.GoogleTypes.getDefaultInstance()) return this;
      if (other.hasTimestampField()) {
        mergeTimestampField(other.getTimestampField());
      }
      if (other.hasDurationField()) {
        mergeDurationField(other.getDurationField());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bkbn.kompendium.protobufjavaconverter.GoogleTypes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bkbn.kompendium.protobufjavaconverter.GoogleTypes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp timestampField_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampFieldBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     * @return Whether the timestampField field is set.
     */
    public boolean hasTimestampField() {
      return timestampFieldBuilder_ != null || timestampField_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     * @return The timestampField.
     */
    public com.google.protobuf.Timestamp getTimestampField() {
      if (timestampFieldBuilder_ == null) {
        return timestampField_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestampField_;
      } else {
        return timestampFieldBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     */
    public Builder setTimestampField(com.google.protobuf.Timestamp value) {
      if (timestampFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestampField_ = value;
        onChanged();
      } else {
        timestampFieldBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     */
    public Builder setTimestampField(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampFieldBuilder_ == null) {
        timestampField_ = builderForValue.build();
        onChanged();
      } else {
        timestampFieldBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     */
    public Builder mergeTimestampField(com.google.protobuf.Timestamp value) {
      if (timestampFieldBuilder_ == null) {
        if (timestampField_ != null) {
          timestampField_ =
            com.google.protobuf.Timestamp.newBuilder(timestampField_).mergeFrom(value).buildPartial();
        } else {
          timestampField_ = value;
        }
        onChanged();
      } else {
        timestampFieldBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     */
    public Builder clearTimestampField() {
      if (timestampFieldBuilder_ == null) {
        timestampField_ = null;
        onChanged();
      } else {
        timestampField_ = null;
        timestampFieldBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampFieldBuilder() {
      
      onChanged();
      return getTimestampFieldFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampFieldOrBuilder() {
      if (timestampFieldBuilder_ != null) {
        return timestampFieldBuilder_.getMessageOrBuilder();
      } else {
        return timestampField_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestampField_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldFieldBuilder() {
      if (timestampFieldBuilder_ == null) {
        timestampFieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestampField(),
                getParentForChildren(),
                isClean());
        timestampField_ = null;
      }
      return timestampFieldBuilder_;
    }

    private com.google.protobuf.Duration durationField_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationFieldBuilder_;
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     * @return Whether the durationField field is set.
     */
    public boolean hasDurationField() {
      return durationFieldBuilder_ != null || durationField_ != null;
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     * @return The durationField.
     */
    public com.google.protobuf.Duration getDurationField() {
      if (durationFieldBuilder_ == null) {
        return durationField_ == null ? com.google.protobuf.Duration.getDefaultInstance() : durationField_;
      } else {
        return durationFieldBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     */
    public Builder setDurationField(com.google.protobuf.Duration value) {
      if (durationFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        durationField_ = value;
        onChanged();
      } else {
        durationFieldBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     */
    public Builder setDurationField(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (durationFieldBuilder_ == null) {
        durationField_ = builderForValue.build();
        onChanged();
      } else {
        durationFieldBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     */
    public Builder mergeDurationField(com.google.protobuf.Duration value) {
      if (durationFieldBuilder_ == null) {
        if (durationField_ != null) {
          durationField_ =
            com.google.protobuf.Duration.newBuilder(durationField_).mergeFrom(value).buildPartial();
        } else {
          durationField_ = value;
        }
        onChanged();
      } else {
        durationFieldBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     */
    public Builder clearDurationField() {
      if (durationFieldBuilder_ == null) {
        durationField_ = null;
        onChanged();
      } else {
        durationField_ = null;
        durationFieldBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     */
    public com.google.protobuf.Duration.Builder getDurationFieldBuilder() {
      
      onChanged();
      return getDurationFieldFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     */
    public com.google.protobuf.DurationOrBuilder getDurationFieldOrBuilder() {
      if (durationFieldBuilder_ != null) {
        return durationFieldBuilder_.getMessageOrBuilder();
      } else {
        return durationField_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : durationField_;
      }
    }
    /**
     * <pre>
     * TODO value types
     * </pre>
     *
     * <code>.google.protobuf.Duration duration_field = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getDurationFieldFieldBuilder() {
      if (durationFieldBuilder_ == null) {
        durationFieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getDurationField(),
                getParentForChildren(),
                isClean());
        durationField_ = null;
      }
      return durationFieldBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.bkbn.kompendium.protobufjavaconverter.GoogleTypes)
  }

  // @@protoc_insertion_point(class_scope:io.bkbn.kompendium.protobufjavaconverter.GoogleTypes)
  private static final io.bkbn.kompendium.protobufjavaconverter.GoogleTypes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bkbn.kompendium.protobufjavaconverter.GoogleTypes();
  }

  public static io.bkbn.kompendium.protobufjavaconverter.GoogleTypes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GoogleTypes>
      PARSER = new com.google.protobuf.AbstractParser<GoogleTypes>() {
    @java.lang.Override
    public GoogleTypes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GoogleTypes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GoogleTypes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GoogleTypes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.GoogleTypes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

