// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public interface GoogleTypesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bkbn.kompendium.protobufjavaconverter.GoogleTypes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
   * @return Whether the timestampField field is set.
   */
  boolean hasTimestampField();
  /**
   * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
   * @return The timestampField.
   */
  com.google.protobuf.Timestamp getTimestampField();
  /**
   * <code>.google.protobuf.Timestamp timestamp_field = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampFieldOrBuilder();

  /**
   * <pre>
   * TODO value types
   * </pre>
   *
   * <code>.google.protobuf.Duration duration_field = 2;</code>
   * @return Whether the durationField field is set.
   */
  boolean hasDurationField();
  /**
   * <pre>
   * TODO value types
   * </pre>
   *
   * <code>.google.protobuf.Duration duration_field = 2;</code>
   * @return The durationField.
   */
  com.google.protobuf.Duration getDurationField();
  /**
   * <pre>
   * TODO value types
   * </pre>
   *
   * <code>.google.protobuf.Duration duration_field = 2;</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationFieldOrBuilder();
}
