// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

/**
 * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage}
 */
public final class NestedMapMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage)
    NestedMapMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NestedMapMessage.newBuilder() to construct.
  private NestedMapMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NestedMapMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NestedMapMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NestedMapMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              mapField_ = com.google.protobuf.MapField.newMapField(
                  MapFieldDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>
            mapField__ = input.readMessage(
                MapFieldDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            mapField_.getMutableMap().put(
                mapField__.getKey(), mapField__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetMapField();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage.class, io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage.Builder.class);
  }

  public static final int MAP_FIELD_FIELD_NUMBER = 1;
  private static final class MapFieldDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>newDefaultInstance(
                io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_MapFieldEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> mapField_;
  private com.google.protobuf.MapField<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>
  internalGetMapField() {
    if (mapField_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapFieldDefaultEntryHolder.defaultEntry);
    }
    return mapField_;
  }

  public int getMapFieldCount() {
    return internalGetMapField().getMap().size();
  }
  /**
   * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
   */

  @java.lang.Override
  public boolean containsMapField(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMapField().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapFieldMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> getMapField() {
    return getMapFieldMap();
  }
  /**
   * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> getMapFieldMap() {
    return internalGetMapField().getMap();
  }
  /**
   * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
   */
  @java.lang.Override

  public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getMapFieldOrDefault(
      java.lang.String key,
      io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> map =
        internalGetMapField().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
   */
  @java.lang.Override

  public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getMapFieldOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> map =
        internalGetMapField().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMapField(),
        MapFieldDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> entry
         : internalGetMapField().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>
      mapField__ = MapFieldDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mapField__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage)) {
      return super.equals(obj);
    }
    io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage other = (io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage) obj;

    if (!internalGetMapField().equals(
        other.internalGetMapField())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetMapField().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMapField().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage)
      io.bkbn.kompendium.protobufjavaconverter.NestedMapMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMapField();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableMapField();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage.class, io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage.Builder.class);
    }

    // Construct using io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableMapField().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_descriptor;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage getDefaultInstanceForType() {
      return io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage build() {
      io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage buildPartial() {
      io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage result = new io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage(this);
      int from_bitField0_ = bitField0_;
      result.mapField_ = internalGetMapField();
      result.mapField_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage) {
        return mergeFrom((io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage other) {
      if (other == io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage.getDefaultInstance()) return this;
      internalGetMutableMapField().mergeFrom(
          other.internalGetMapField());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> mapField_;
    private com.google.protobuf.MapField<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>
    internalGetMapField() {
      if (mapField_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapFieldDefaultEntryHolder.defaultEntry);
      }
      return mapField_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>
    internalGetMutableMapField() {
      onChanged();;
      if (mapField_ == null) {
        mapField_ = com.google.protobuf.MapField.newMapField(
            MapFieldDefaultEntryHolder.defaultEntry);
      }
      if (!mapField_.isMutable()) {
        mapField_ = mapField_.copy();
      }
      return mapField_;
    }

    public int getMapFieldCount() {
      return internalGetMapField().getMap().size();
    }
    /**
     * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
     */

    @java.lang.Override
    public boolean containsMapField(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMapField().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapFieldMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> getMapField() {
      return getMapFieldMap();
    }
    /**
     * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> getMapFieldMap() {
      return internalGetMapField().getMap();
    }
    /**
     * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
     */
    @java.lang.Override

    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getMapFieldOrDefault(
        java.lang.String key,
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> map =
          internalGetMapField().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
     */
    @java.lang.Override

    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getMapFieldOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> map =
          internalGetMapField().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMapField() {
      internalGetMutableMapField().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
     */

    public Builder removeMapField(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMapField().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>
    getMutableMapField() {
      return internalGetMutableMapField().getMutableMap();
    }
    /**
     * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
     */
    public Builder putMapField(
        java.lang.String key,
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMapField().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage&gt; map_field = 1;</code>
     */

    public Builder putAllMapField(
        java.util.Map<java.lang.String, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> values) {
      internalGetMutableMapField().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage)
  }

  // @@protoc_insertion_point(class_scope:io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage)
  private static final io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage();
  }

  public static io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NestedMapMessage>
      PARSER = new com.google.protobuf.AbstractParser<NestedMapMessage>() {
    @java.lang.Override
    public NestedMapMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NestedMapMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NestedMapMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NestedMapMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.NestedMapMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

