// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

/**
 * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.NestedMessage}
 */
public final class NestedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.bkbn.kompendium.protobufjavaconverter.NestedMessage)
    NestedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NestedMessage.newBuilder() to construct.
  private NestedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NestedMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NestedMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NestedMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder subBuilder = null;
            if (nestedField_ != null) {
              subBuilder = nestedField_.toBuilder();
            }
            nestedField_ = input.readMessage(io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nestedField_);
              nestedField_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bkbn.kompendium.protobufjavaconverter.NestedMessage.class, io.bkbn.kompendium.protobufjavaconverter.NestedMessage.Builder.class);
  }

  public static final int NESTED_FIELD_FIELD_NUMBER = 1;
  private io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nestedField_;
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
   * @return Whether the nestedField field is set.
   */
  @java.lang.Override
  public boolean hasNestedField() {
    return nestedField_ != null;
  }
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
   * @return The nestedField.
   */
  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getNestedField() {
    return nestedField_ == null ? io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.getDefaultInstance() : nestedField_;
  }
  /**
   * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
   */
  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder getNestedFieldOrBuilder() {
    return getNestedField();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nestedField_ != null) {
      output.writeMessage(1, getNestedField());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nestedField_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNestedField());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bkbn.kompendium.protobufjavaconverter.NestedMessage)) {
      return super.equals(obj);
    }
    io.bkbn.kompendium.protobufjavaconverter.NestedMessage other = (io.bkbn.kompendium.protobufjavaconverter.NestedMessage) obj;

    if (hasNestedField() != other.hasNestedField()) return false;
    if (hasNestedField()) {
      if (!getNestedField()
          .equals(other.getNestedField())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNestedField()) {
      hash = (37 * hash) + NESTED_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getNestedField().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bkbn.kompendium.protobufjavaconverter.NestedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.NestedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bkbn.kompendium.protobufjavaconverter.NestedMessage)
      io.bkbn.kompendium.protobufjavaconverter.NestedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bkbn.kompendium.protobufjavaconverter.NestedMessage.class, io.bkbn.kompendium.protobufjavaconverter.NestedMessage.Builder.class);
    }

    // Construct using io.bkbn.kompendium.protobufjavaconverter.NestedMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nestedFieldBuilder_ == null) {
        nestedField_ = null;
      } else {
        nestedField_ = null;
        nestedFieldBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_descriptor;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.NestedMessage getDefaultInstanceForType() {
      return io.bkbn.kompendium.protobufjavaconverter.NestedMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.NestedMessage build() {
      io.bkbn.kompendium.protobufjavaconverter.NestedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.NestedMessage buildPartial() {
      io.bkbn.kompendium.protobufjavaconverter.NestedMessage result = new io.bkbn.kompendium.protobufjavaconverter.NestedMessage(this);
      if (nestedFieldBuilder_ == null) {
        result.nestedField_ = nestedField_;
      } else {
        result.nestedField_ = nestedFieldBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bkbn.kompendium.protobufjavaconverter.NestedMessage) {
        return mergeFrom((io.bkbn.kompendium.protobufjavaconverter.NestedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bkbn.kompendium.protobufjavaconverter.NestedMessage other) {
      if (other == io.bkbn.kompendium.protobufjavaconverter.NestedMessage.getDefaultInstance()) return this;
      if (other.hasNestedField()) {
        mergeNestedField(other.getNestedField());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bkbn.kompendium.protobufjavaconverter.NestedMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bkbn.kompendium.protobufjavaconverter.NestedMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nestedField_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder> nestedFieldBuilder_;
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     * @return Whether the nestedField field is set.
     */
    public boolean hasNestedField() {
      return nestedFieldBuilder_ != null || nestedField_ != null;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     * @return The nestedField.
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getNestedField() {
      if (nestedFieldBuilder_ == null) {
        return nestedField_ == null ? io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.getDefaultInstance() : nestedField_;
      } else {
        return nestedFieldBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     */
    public Builder setNestedField(io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage value) {
      if (nestedFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nestedField_ = value;
        onChanged();
      } else {
        nestedFieldBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     */
    public Builder setNestedField(
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder builderForValue) {
      if (nestedFieldBuilder_ == null) {
        nestedField_ = builderForValue.build();
        onChanged();
      } else {
        nestedFieldBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     */
    public Builder mergeNestedField(io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage value) {
      if (nestedFieldBuilder_ == null) {
        if (nestedField_ != null) {
          nestedField_ =
            io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.newBuilder(nestedField_).mergeFrom(value).buildPartial();
        } else {
          nestedField_ = value;
        }
        onChanged();
      } else {
        nestedFieldBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     */
    public Builder clearNestedField() {
      if (nestedFieldBuilder_ == null) {
        nestedField_ = null;
        onChanged();
      } else {
        nestedField_ = null;
        nestedFieldBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder getNestedFieldBuilder() {
      
      onChanged();
      return getNestedFieldFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder getNestedFieldOrBuilder() {
      if (nestedFieldBuilder_ != null) {
        return nestedFieldBuilder_.getMessageOrBuilder();
      } else {
        return nestedField_ == null ?
            io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.getDefaultInstance() : nestedField_;
      }
    }
    /**
     * <code>.io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage nested_field = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder> 
        getNestedFieldFieldBuilder() {
      if (nestedFieldBuilder_ == null) {
        nestedFieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder>(
                getNestedField(),
                getParentForChildren(),
                isClean());
        nestedField_ = null;
      }
      return nestedFieldBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.bkbn.kompendium.protobufjavaconverter.NestedMessage)
  }

  // @@protoc_insertion_point(class_scope:io.bkbn.kompendium.protobufjavaconverter.NestedMessage)
  private static final io.bkbn.kompendium.protobufjavaconverter.NestedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bkbn.kompendium.protobufjavaconverter.NestedMessage();
  }

  public static io.bkbn.kompendium.protobufjavaconverter.NestedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NestedMessage>
      PARSER = new com.google.protobuf.AbstractParser<NestedMessage>() {
    @java.lang.Override
    public NestedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NestedMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NestedMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NestedMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.NestedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

