// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public interface RepeatedEnumMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @return A list containing the repeatedField.
   */
  java.util.List<io.bkbn.kompendium.protobufjavaconverter.Corpus> getRepeatedFieldList();
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @return The count of repeatedField.
   */
  int getRepeatedFieldCount();
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @param index The index of the element to return.
   * @return The repeatedField at the given index.
   */
  io.bkbn.kompendium.protobufjavaconverter.Corpus getRepeatedField(int index);
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @return A list containing the enum numeric values on the wire for repeatedField.
   */
  java.util.List<java.lang.Integer>
  getRepeatedFieldValueList();
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of repeatedField at the given index.
   */
  int getRepeatedFieldValue(int index);
}
