// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

/**
 * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage}
 */
public final class RepeatedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage)
    RepeatedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RepeatedMessage.newBuilder() to construct.
  private RepeatedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RepeatedMessage() {
    repeatedField_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RepeatedMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RepeatedMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              repeatedField_ = new java.util.ArrayList<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            repeatedField_.add(
                input.readMessage(io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        repeatedField_ = java.util.Collections.unmodifiableList(repeatedField_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage.class, io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage.Builder.class);
  }

  public static final int REPEATED_FIELD_FIELD_NUMBER = 1;
  private java.util.List<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> repeatedField_;
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> getRepeatedFieldList() {
    return repeatedField_;
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder> 
      getRepeatedFieldOrBuilderList() {
    return repeatedField_;
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  @java.lang.Override
  public int getRepeatedFieldCount() {
    return repeatedField_.size();
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getRepeatedField(int index) {
    return repeatedField_.get(index);
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder getRepeatedFieldOrBuilder(
      int index) {
    return repeatedField_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < repeatedField_.size(); i++) {
      output.writeMessage(1, repeatedField_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < repeatedField_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, repeatedField_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage)) {
      return super.equals(obj);
    }
    io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage other = (io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage) obj;

    if (!getRepeatedFieldList()
        .equals(other.getRepeatedFieldList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRepeatedFieldCount() > 0) {
      hash = (37 * hash) + REPEATED_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getRepeatedFieldList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage)
      io.bkbn.kompendium.protobufjavaconverter.RepeatedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage.class, io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage.Builder.class);
    }

    // Construct using io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRepeatedFieldFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (repeatedFieldBuilder_ == null) {
        repeatedField_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        repeatedFieldBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_descriptor;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage getDefaultInstanceForType() {
      return io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage build() {
      io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage buildPartial() {
      io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage result = new io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage(this);
      int from_bitField0_ = bitField0_;
      if (repeatedFieldBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          repeatedField_ = java.util.Collections.unmodifiableList(repeatedField_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.repeatedField_ = repeatedField_;
      } else {
        result.repeatedField_ = repeatedFieldBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage) {
        return mergeFrom((io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage other) {
      if (other == io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage.getDefaultInstance()) return this;
      if (repeatedFieldBuilder_ == null) {
        if (!other.repeatedField_.isEmpty()) {
          if (repeatedField_.isEmpty()) {
            repeatedField_ = other.repeatedField_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRepeatedFieldIsMutable();
            repeatedField_.addAll(other.repeatedField_);
          }
          onChanged();
        }
      } else {
        if (!other.repeatedField_.isEmpty()) {
          if (repeatedFieldBuilder_.isEmpty()) {
            repeatedFieldBuilder_.dispose();
            repeatedFieldBuilder_ = null;
            repeatedField_ = other.repeatedField_;
            bitField0_ = (bitField0_ & ~0x00000001);
            repeatedFieldBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRepeatedFieldFieldBuilder() : null;
          } else {
            repeatedFieldBuilder_.addAllMessages(other.repeatedField_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> repeatedField_ =
      java.util.Collections.emptyList();
    private void ensureRepeatedFieldIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        repeatedField_ = new java.util.ArrayList<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage>(repeatedField_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder> repeatedFieldBuilder_;

    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public java.util.List<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> getRepeatedFieldList() {
      if (repeatedFieldBuilder_ == null) {
        return java.util.Collections.unmodifiableList(repeatedField_);
      } else {
        return repeatedFieldBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public int getRepeatedFieldCount() {
      if (repeatedFieldBuilder_ == null) {
        return repeatedField_.size();
      } else {
        return repeatedFieldBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getRepeatedField(int index) {
      if (repeatedFieldBuilder_ == null) {
        return repeatedField_.get(index);
      } else {
        return repeatedFieldBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder setRepeatedField(
        int index, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage value) {
      if (repeatedFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepeatedFieldIsMutable();
        repeatedField_.set(index, value);
        onChanged();
      } else {
        repeatedFieldBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder setRepeatedField(
        int index, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder builderForValue) {
      if (repeatedFieldBuilder_ == null) {
        ensureRepeatedFieldIsMutable();
        repeatedField_.set(index, builderForValue.build());
        onChanged();
      } else {
        repeatedFieldBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder addRepeatedField(io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage value) {
      if (repeatedFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepeatedFieldIsMutable();
        repeatedField_.add(value);
        onChanged();
      } else {
        repeatedFieldBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder addRepeatedField(
        int index, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage value) {
      if (repeatedFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepeatedFieldIsMutable();
        repeatedField_.add(index, value);
        onChanged();
      } else {
        repeatedFieldBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder addRepeatedField(
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder builderForValue) {
      if (repeatedFieldBuilder_ == null) {
        ensureRepeatedFieldIsMutable();
        repeatedField_.add(builderForValue.build());
        onChanged();
      } else {
        repeatedFieldBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder addRepeatedField(
        int index, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder builderForValue) {
      if (repeatedFieldBuilder_ == null) {
        ensureRepeatedFieldIsMutable();
        repeatedField_.add(index, builderForValue.build());
        onChanged();
      } else {
        repeatedFieldBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder addAllRepeatedField(
        java.lang.Iterable<? extends io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> values) {
      if (repeatedFieldBuilder_ == null) {
        ensureRepeatedFieldIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, repeatedField_);
        onChanged();
      } else {
        repeatedFieldBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder clearRepeatedField() {
      if (repeatedFieldBuilder_ == null) {
        repeatedField_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        repeatedFieldBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public Builder removeRepeatedField(int index) {
      if (repeatedFieldBuilder_ == null) {
        ensureRepeatedFieldIsMutable();
        repeatedField_.remove(index);
        onChanged();
      } else {
        repeatedFieldBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder getRepeatedFieldBuilder(
        int index) {
      return getRepeatedFieldFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder getRepeatedFieldOrBuilder(
        int index) {
      if (repeatedFieldBuilder_ == null) {
        return repeatedField_.get(index);  } else {
        return repeatedFieldBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public java.util.List<? extends io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder> 
         getRepeatedFieldOrBuilderList() {
      if (repeatedFieldBuilder_ != null) {
        return repeatedFieldBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(repeatedField_);
      }
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder addRepeatedFieldBuilder() {
      return getRepeatedFieldFieldBuilder().addBuilder(
          io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder addRepeatedFieldBuilder(
        int index) {
      return getRepeatedFieldFieldBuilder().addBuilder(
          index, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
     */
    public java.util.List<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder> 
         getRepeatedFieldBuilderList() {
      return getRepeatedFieldFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder> 
        getRepeatedFieldFieldBuilder() {
      if (repeatedFieldBuilder_ == null) {
        repeatedFieldBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage.Builder, io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder>(
                repeatedField_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        repeatedField_ = null;
      }
      return repeatedFieldBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage)
  }

  // @@protoc_insertion_point(class_scope:io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage)
  private static final io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage();
  }

  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepeatedMessage>
      PARSER = new com.google.protobuf.AbstractParser<RepeatedMessage>() {
    @java.lang.Override
    public RepeatedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RepeatedMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RepeatedMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepeatedMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

