// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public interface RepeatedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bkbn.kompendium.protobufjavaconverter.RepeatedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  java.util.List<io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage> 
      getRepeatedFieldList();
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage getRepeatedField(int index);
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  int getRepeatedFieldCount();
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  java.util.List<? extends io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder> 
      getRepeatedFieldOrBuilderList();
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage repeated_field = 1;</code>
   */
  io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessageOrBuilder getRepeatedFieldOrBuilder(
      int index);
}
