// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

/**
 * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage}
 */
public final class RepeatedEnumMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage)
    RepeatedEnumMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RepeatedEnumMessage.newBuilder() to construct.
  private RepeatedEnumMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RepeatedEnumMessage() {
    repeatedField_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RepeatedEnumMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RepeatedEnumMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              repeatedField_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            repeatedField_.add(rawValue);
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                repeatedField_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              repeatedField_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        repeatedField_ = java.util.Collections.unmodifiableList(repeatedField_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage.class, io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage.Builder.class);
  }

  public static final int REPEATED_FIELD_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> repeatedField_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, io.bkbn.kompendium.protobufjavaconverter.Corpus> repeatedField_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, io.bkbn.kompendium.protobufjavaconverter.Corpus>() {
            public io.bkbn.kompendium.protobufjavaconverter.Corpus convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              io.bkbn.kompendium.protobufjavaconverter.Corpus result = io.bkbn.kompendium.protobufjavaconverter.Corpus.valueOf(from);
              return result == null ? io.bkbn.kompendium.protobufjavaconverter.Corpus.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @return A list containing the repeatedField.
   */
  @java.lang.Override
  public java.util.List<io.bkbn.kompendium.protobufjavaconverter.Corpus> getRepeatedFieldList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, io.bkbn.kompendium.protobufjavaconverter.Corpus>(repeatedField_, repeatedField_converter_);
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @return The count of repeatedField.
   */
  @java.lang.Override
  public int getRepeatedFieldCount() {
    return repeatedField_.size();
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @param index The index of the element to return.
   * @return The repeatedField at the given index.
   */
  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.Corpus getRepeatedField(int index) {
    return repeatedField_converter_.convert(repeatedField_.get(index));
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @return A list containing the enum numeric values on the wire for repeatedField.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getRepeatedFieldValueList() {
    return repeatedField_;
  }
  /**
   * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of repeatedField at the given index.
   */
  @java.lang.Override
  public int getRepeatedFieldValue(int index) {
    return repeatedField_.get(index);
  }
  private int repeatedFieldMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getRepeatedFieldList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(repeatedFieldMemoizedSerializedSize);
    }
    for (int i = 0; i < repeatedField_.size(); i++) {
      output.writeEnumNoTag(repeatedField_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < repeatedField_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(repeatedField_.get(i));
      }
      size += dataSize;
      if (!getRepeatedFieldList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }repeatedFieldMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage)) {
      return super.equals(obj);
    }
    io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage other = (io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage) obj;

    if (!repeatedField_.equals(other.repeatedField_)) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRepeatedFieldCount() > 0) {
      hash = (37 * hash) + REPEATED_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + repeatedField_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage)
      io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage.class, io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage.Builder.class);
    }

    // Construct using io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      repeatedField_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bkbn.kompendium.protobufjavaconverter.Test.internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_descriptor;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage getDefaultInstanceForType() {
      return io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage build() {
      io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage buildPartial() {
      io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage result = new io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        repeatedField_ = java.util.Collections.unmodifiableList(repeatedField_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.repeatedField_ = repeatedField_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage) {
        return mergeFrom((io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage other) {
      if (other == io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage.getDefaultInstance()) return this;
      if (!other.repeatedField_.isEmpty()) {
        if (repeatedField_.isEmpty()) {
          repeatedField_ = other.repeatedField_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRepeatedFieldIsMutable();
          repeatedField_.addAll(other.repeatedField_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> repeatedField_ =
      java.util.Collections.emptyList();
    private void ensureRepeatedFieldIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        repeatedField_ = new java.util.ArrayList<java.lang.Integer>(repeatedField_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @return A list containing the repeatedField.
     */
    public java.util.List<io.bkbn.kompendium.protobufjavaconverter.Corpus> getRepeatedFieldList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, io.bkbn.kompendium.protobufjavaconverter.Corpus>(repeatedField_, repeatedField_converter_);
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @return The count of repeatedField.
     */
    public int getRepeatedFieldCount() {
      return repeatedField_.size();
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param index The index of the element to return.
     * @return The repeatedField at the given index.
     */
    public io.bkbn.kompendium.protobufjavaconverter.Corpus getRepeatedField(int index) {
      return repeatedField_converter_.convert(repeatedField_.get(index));
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param index The index to set the value at.
     * @param value The repeatedField to set.
     * @return This builder for chaining.
     */
    public Builder setRepeatedField(
        int index, io.bkbn.kompendium.protobufjavaconverter.Corpus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRepeatedFieldIsMutable();
      repeatedField_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param value The repeatedField to add.
     * @return This builder for chaining.
     */
    public Builder addRepeatedField(io.bkbn.kompendium.protobufjavaconverter.Corpus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRepeatedFieldIsMutable();
      repeatedField_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param values The repeatedField to add.
     * @return This builder for chaining.
     */
    public Builder addAllRepeatedField(
        java.lang.Iterable<? extends io.bkbn.kompendium.protobufjavaconverter.Corpus> values) {
      ensureRepeatedFieldIsMutable();
      for (io.bkbn.kompendium.protobufjavaconverter.Corpus value : values) {
        repeatedField_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepeatedField() {
      repeatedField_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @return A list containing the enum numeric values on the wire for repeatedField.
     */
    public java.util.List<java.lang.Integer>
    getRepeatedFieldValueList() {
      return java.util.Collections.unmodifiableList(repeatedField_);
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of repeatedField at the given index.
     */
    public int getRepeatedFieldValue(int index) {
      return repeatedField_.get(index);
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of repeatedField at the given index.
     * @return This builder for chaining.
     */
    public Builder setRepeatedFieldValue(
        int index, int value) {
      ensureRepeatedFieldIsMutable();
      repeatedField_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param value The enum numeric value on the wire for repeatedField to add.
     * @return This builder for chaining.
     */
    public Builder addRepeatedFieldValue(int value) {
      ensureRepeatedFieldIsMutable();
      repeatedField_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .io.bkbn.kompendium.protobufjavaconverter.Corpus repeated_field = 1;</code>
     * @param values The enum numeric values on the wire for repeatedField to add.
     * @return This builder for chaining.
     */
    public Builder addAllRepeatedFieldValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureRepeatedFieldIsMutable();
      for (int value : values) {
        repeatedField_.add(value);
      }
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage)
  }

  // @@protoc_insertion_point(class_scope:io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage)
  private static final io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage();
  }

  public static io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepeatedEnumMessage>
      PARSER = new com.google.protobuf.AbstractParser<RepeatedEnumMessage>() {
    @java.lang.Override
    public RepeatedEnumMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RepeatedEnumMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RepeatedEnumMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepeatedEnumMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.bkbn.kompendium.protobufjavaconverter.RepeatedEnumMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

