// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public interface SimpleTestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bkbn.kompendium.protobufjavaconverter.SimpleTestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double my_test_double = 1;</code>
   * @return The myTestDouble.
   */
  double getMyTestDouble();

  /**
   * <code>float my_test_float = 2;</code>
   * @return The myTestFloat.
   */
  float getMyTestFloat();

  /**
   * <code>int32 my_test_int32 = 3;</code>
   * @return The myTestInt32.
   */
  int getMyTestInt32();

  /**
   * <code>int64 my_test_int64 = 4;</code>
   * @return The myTestInt64.
   */
  long getMyTestInt64();

  /**
   * <code>uint32 my_test_uint32 = 5;</code>
   * @return The myTestUint32.
   */
  int getMyTestUint32();

  /**
   * <code>uint64 my_test_uint64 = 6;</code>
   * @return The myTestUint64.
   */
  long getMyTestUint64();

  /**
   * <code>sint32 my_test_sint32 = 7;</code>
   * @return The myTestSint32.
   */
  int getMyTestSint32();

  /**
   * <code>sint64 my_test_sint64 = 8;</code>
   * @return The myTestSint64.
   */
  long getMyTestSint64();

  /**
   * <code>fixed32 my_test_fixed32 = 9;</code>
   * @return The myTestFixed32.
   */
  int getMyTestFixed32();

  /**
   * <code>fixed64 my_test_fixed64 = 10;</code>
   * @return The myTestFixed64.
   */
  long getMyTestFixed64();

  /**
   * <code>sfixed32 my_test_sfixed32 = 11;</code>
   * @return The myTestSfixed32.
   */
  int getMyTestSfixed32();

  /**
   * <code>sfixed64 my_test_sfixed64 = 12;</code>
   * @return The myTestSfixed64.
   */
  long getMyTestSfixed64();

  /**
   * <code>bool my_test_bool = 13;</code>
   * @return The myTestBool.
   */
  boolean getMyTestBool();

  /**
   * <code>bytes my_test_bytes = 14;</code>
   * @return The myTestBytes.
   */
  com.google.protobuf.ByteString getMyTestBytes();

  /**
   * <code>string my_test_string = 15;</code>
   * @return The myTestString.
   */
  java.lang.String getMyTestString();
  /**
   * <code>string my_test_string = 15;</code>
   * @return The bytes for myTestString.
   */
  com.google.protobuf.ByteString
      getMyTestStringBytes();
}
