// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public interface SimpleMapMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bkbn.kompendium.protobufjavaconverter.SimpleMapMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, int32&gt; map_field = 1;</code>
   */
  int getMapFieldCount();
  /**
   * <code>map&lt;string, int32&gt; map_field = 1;</code>
   */
  boolean containsMapField(
      java.lang.String key);
  /**
   * Use {@link #getMapFieldMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getMapField();
  /**
   * <code>map&lt;string, int32&gt; map_field = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getMapFieldMap();
  /**
   * <code>map&lt;string, int32&gt; map_field = 1;</code>
   */

  int getMapFieldOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; map_field = 1;</code>
   */

  int getMapFieldOrThrow(
      java.lang.String key);
}
