// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/bkbn/kompendium/protobufjavaconverter/converters/test.proto

package io.bkbn.kompendium.protobufjavaconverter;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleTestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleTestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_DoubleNestedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_DoubleNestedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_MapFieldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_MapFieldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_MapFieldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_MapFieldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>io/bkbn/kompendium/protobufjavaconvert" +
      "er/converters/test.proto\022(io.bkbn.kompen" +
      "dium.protobufjavaconverter\032\037google/proto" +
      "buf/timestamp.proto\032\036google/protobuf/dur" +
      "ation.proto\"\373\002\n\021SimpleTestMessage\022\026\n\016my_" +
      "test_double\030\001 \001(\001\022\025\n\rmy_test_float\030\002 \001(\002" +
      "\022\025\n\rmy_test_int32\030\003 \001(\005\022\025\n\rmy_test_int64" +
      "\030\004 \001(\003\022\026\n\016my_test_uint32\030\005 \001(\r\022\026\n\016my_tes" +
      "t_uint64\030\006 \001(\004\022\026\n\016my_test_sint32\030\007 \001(\021\022\026" +
      "\n\016my_test_sint64\030\010 \001(\022\022\027\n\017my_test_fixed3" +
      "2\030\t \001(\007\022\027\n\017my_test_fixed64\030\n \001(\006\022\030\n\020my_t" +
      "est_sfixed32\030\013 \001(\017\022\030\n\020my_test_sfixed64\030\014" +
      " \001(\020\022\024\n\014my_test_bool\030\r \001(\010\022\025\n\rmy_test_by" +
      "tes\030\016 \001(\014\022\026\n\016my_test_string\030\017 \001(\t\"O\n\013Enu" +
      "mMessage\022@\n\006corpus\030\001 \001(\01620.io.bkbn.kompe" +
      "ndium.protobufjavaconverter.Corpus\"b\n\rNe" +
      "stedMessage\022Q\n\014nested_field\030\001 \001(\0132;.io.b" +
      "kbn.kompendium.protobufjavaconverter.Sim" +
      "pleTestMessage\"d\n\023DoubleNestedMessage\022M\n" +
      "\014nested_field\030\001 \001(\01327.io.bkbn.kompendium" +
      ".protobufjavaconverter.NestedMessage\"f\n\017" +
      "RepeatedMessage\022S\n\016repeated_field\030\001 \003(\0132" +
      ";.io.bkbn.kompendium.protobufjavaconvert" +
      "er.SimpleTestMessage\"_\n\023RepeatedEnumMess" +
      "age\022H\n\016repeated_field\030\001 \003(\01620.io.bkbn.ko" +
      "mpendium.protobufjavaconverter.Corpus\"\240\001" +
      "\n\020SimpleMapMessage\022[\n\tmap_field\030\001 \003(\0132H." +
      "io.bkbn.kompendium.protobufjavaconverter" +
      ".SimpleMapMessage.MapFieldEntry\032/\n\rMapFi" +
      "eldEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001" +
      "\"\335\001\n\020NestedMapMessage\022[\n\tmap_field\030\001 \003(\013" +
      "2H.io.bkbn.kompendium.protobufjavaconver" +
      "ter.NestedMapMessage.MapFieldEntry\032l\n\rMa" +
      "pFieldEntry\022\013\n\003key\030\001 \001(\t\022J\n\005value\030\002 \001(\0132" +
      ";.io.bkbn.kompendium.protobufjavaconvert" +
      "er.SimpleTestMessage:\0028\001\"u\n\013GoogleTypes\022" +
      "3\n\017timestamp_field\030\001 \001(\0132\032.google.protob" +
      "uf.Timestamp\0221\n\016duration_field\030\002 \001(\0132\031.g" +
      "oogle.protobuf.Duration*\243\001\n\006Corpus\022\026\n\022CO" +
      "RPUS_UNSPECIFIED\020\000\022\024\n\020CORPUS_UNIVERSAL\020\001" +
      "\022\016\n\nCORPUS_WEB\020\002\022\021\n\rCORPUS_IMAGES\020\003\022\020\n\014C" +
      "ORPUS_LOCAL\020\004\022\017\n\013CORPUS_NEWS\020\005\022\023\n\017CORPUS" +
      "_PRODUCTS\020\006\022\020\n\014CORPUS_VIDEO\020\007B,\n(io.bkbn" +
      ".kompendium.protobufjavaconverterP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleTestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleTestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleTestMessage_descriptor,
        new java.lang.String[] { "MyTestDouble", "MyTestFloat", "MyTestInt32", "MyTestInt64", "MyTestUint32", "MyTestUint64", "MyTestSint32", "MyTestSint64", "MyTestFixed32", "MyTestFixed64", "MyTestSfixed32", "MyTestSfixed64", "MyTestBool", "MyTestBytes", "MyTestString", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_EnumMessage_descriptor,
        new java.lang.String[] { "Corpus", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMessage_descriptor,
        new java.lang.String[] { "NestedField", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_DoubleNestedMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_DoubleNestedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_DoubleNestedMessage_descriptor,
        new java.lang.String[] { "NestedField", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedMessage_descriptor,
        new java.lang.String[] { "RepeatedField", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_RepeatedEnumMessage_descriptor,
        new java.lang.String[] { "RepeatedField", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_descriptor,
        new java.lang.String[] { "MapField", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_MapFieldEntry_descriptor =
      internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_descriptor.getNestedTypes().get(0);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_SimpleMapMessage_MapFieldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_descriptor,
        new java.lang.String[] { "MapField", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_MapFieldEntry_descriptor =
      internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_descriptor.getNestedTypes().get(0);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_NestedMapMessage_MapFieldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_bkbn_kompendium_protobufjavaconverter_GoogleTypes_descriptor,
        new java.lang.String[] { "TimestampField", "DurationField", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
