/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kompendium

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertEquals(classUnderTest.someLibraryMethod(), "Heya", "someLibraryMethod should return 'true'")
    }
}
